### ISSUE TITLE
Replace UINT16 by UINT8 for variables that have small values

### ISSUE THREAD

**Issue by AntonioND** [Zal0/GBSoundDemo#1]
There are lots of variables in this struct (most of them) that could be made 8-bit variables:

https://github.com/Zal0/GBSoundDemo/blob/38082e296dc26a8ef368892d77a9f1b9f8ac4258/sound.c#L175-L293

**Comment by Zal0** [comment]
I know the code is really ugly... but the compiler had some serious issues here so I had to change all of them into UINT16 and that way everything worked
Yes, gbdk sucks... a lot
